language: node_js

cache:
  directories:
    - webapp/elm-stuff/packages
    - webapp/tests/elm-stuff/packages
    - sysconfcpus

node_js:
  - "node"

install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install -g elm@0.18.0 elm-test
  - pushd webapp
  - npm install
  - elm package install -y
  - popd

script:
  - pushd webapp
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run build
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run test
  - popd
