language: node_js

cache:
  directories:
    - elm-stuff/packages
    - tests/elm-stuff/packages

node_js:
  - "node"

install:
  - npm install -g elm@0.18.0 elm-test
  - pushd webapp
  - npm install
  - elm package install -y
  - popd

script:
  - pushd webapp
  - npm run build
  - npm run test
  - popd
